Use different action for reporting results
Signed-off-by: Akshath Kothari <akshath.kothari@levo.ai>

diff --git a/schema-conformance/action.yaml b/schema-conformance/action.yaml
--- a/schema-conformance/action.yaml
+++ b/schema-conformance/action.yaml
@@ -1,5 +1,5 @@
 name: "Levo Conformance Action"
-description: "Run Levo conformance tests in your Github workflows"
+description: "Run Levo Schema Conformance tests in your Github workflows"
 inputs:
   schema:
     description: 'URL or path to the OAS schema file'
@@ -16,7 +16,7 @@ inputs:
   fail-on-failed-tests:
     description: 'Fail action on failed test cases. Default: true'
     required: true
-    default: true
+    default: 'true'
   saas-url:
     description: 'Saas url to report results back'
     required: true
@@ -24,7 +24,7 @@ inputs:
   report:
     description: 'Report schema conformance run result to Saas'
     required: false
-    default: true
+    default: 'true'
   cli_extra_args:
     description: 'CLI extra arguments. E.g: -H "Authorization: Bearer 123'
     required: false
@@ -32,26 +32,20 @@ inputs:
   debug:
     description: 'Debug action'
     required: false
-    default: false
+    default: 'false'
 outputs:
   success:
-    description: 'Succeded test cases'
-    value: ${{ steps.map-outputs.outputs.success }}
+    description: 'Succeeded test cases'
+    value: ${{ steps.test-summary.outputs.passed }}
   failed:
     description: 'Failed test cases'
-    value: ${{ steps.map-outputs.outputs.failed }}
-  error:
-    description: 'Errored test cases'
-    value: ${{ steps.map-outputs.outputs.error }}
+    value: ${{ steps.test-summary.outputs.failed }}
   skipped:
     description: 'Skipped test cases'
-    value: ${{ steps.map-outputs.outputs.skip }}
+    value: ${{ steps.test-summary.outputs.skipped }}
   total:
     description: 'Total test cases'
-    value: ${{ steps.map-outputs.outputs.total }}
-  json:
-    description: 'EnricoMi/publish-unit-test-result action JSON output'
-    value: ${{ steps.publish-junit.outputs.json }}
+    value: ${{ steps.test-summary.outputs.total }}
 runs:
   using: 'composite'
   steps:
@@ -85,34 +79,17 @@ runs:
         eval $CMD
         exit 0
       shell: bash
-    - id: reporting
-      if: always()
-      run: |
-        if ${{ inputs.fail-on-failed-tests == 'true' }}; then
-          echo "::set-output name=fail_on::$(echo 'test failures')"
-        fi
-        if ${{ inputs.fail-on-failed-tests != 'true' }}; then
-          echo "::set-output name=fail_on::$(echo 'nothing')"
-        fi
-      shell: bash
     - name: Publish Test Results
-      id: publish-junit
+      id: test-summary
       if: always()
-      uses: EnricoMi/publish-unit-test-result-action@v2
+      uses: test-summary/action@v2
       with:
-        junit_files: '**/reports/*.xml'
-        fail_on: ${{ steps.reporting.outputs.fail_on }}
-        check_run_annotations: 'none'
-        check_name: "Levo Schema Conformance Results"
-    - if: ${{ inputs.debug }}
+        paths: '**/reports/*.xml'
+    - if: inputs.debug == 'true'
       run: cat $PWD/reports/junit.xml
       shell: bash
-    - id: map-outputs
-      if: always()
+    - if: inputs.fail-on-failed-tests == 'true' && steps.test-summary.outputs.failed > 0
       run: |
-        echo "success=${{ fromJSON(steps.publish-junit.outputs.json).stats.tests_succ }}" >> $GITHUB_OUTPUT
-        echo "failed=${{ fromJSON(steps.publish-junit.outputs.json).stats.tests_fail }}" >> $GITHUB_OUTPUT
-        echo "error=${{ fromJSON(steps.publish-junit.outputs.json).stats.tests_error }}" >> $GITHUB_OUTPUT
-        echo "skip=${{ fromJSON(steps.publish-junit.outputs.json).stats.tests_skip }}" >> $GITHUB_OUTPUT
-        echo "total=${{ fromJSON(steps.publish-junit.outputs.json).stats.tests }}" >> $GITHUB_OUTPUT
+        echo "::error::${{ steps.test-summary.outputs.failed }} tests failed."
+        exit 1
       shell: bash
